### ISSUE TITLE
Where does pt_means come from?

### ISSUE THREAD

**Issue by taka-taka-taka** [kthohr/BMR#47]
Hello, Mr O'Hara!
First and foremost let me thank you for the package which I found to be the most useful tool when creating BVARs in R. What I'm curious about is how does the package calculate alpha_pt_mean. I thought it has to be the mean of all draws from the Gibbs sampling procedure, but when I apply bvar_obj$gibbs(1), thus yielding a single beta_draw which is the mean of itself, it does not equal to alpha_pt_means. Are those numbers being estimated via analytical approach?
Just in case, the example is as follows
```r
data(BMRVARData)
bvar_data <- data.matrix(USMacroData[,2:4])
coef_prior <- c(0.9,0.9,0.9)
bvar_obj <- new(bvarm)
bvar_obj$build(bvar_data,TRUE,4)
bvar_obj$prior(coef_prior,1,1,0.5,0.5,100.0,1.0)
bvar_obj$gibbs(1)
bvar_obj$beta_draws
matrix(bvar_obj$alpha_pt_mean,ncol=3)
```
Thank you in advance!

**Comment by kthohr** [comment]
In the BVARM case, the posterior distribution of the coefficients is known in closed-form. `alpha_pt_mean` is the mean of this distribution; see here:

https://github.com/kthohr/BMR/blob/master/src/bmlib/src/var/bvarm.cpp#L258

Due to sampling variation, it need not equal the mean of `beta_draws` (which are just draws from a multivariate normal parameterized by `alpha_pt_mean`).
